name: online_attendence_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  lottie: ^1.4.2
  geolocator: ^9.0.1
  flutter_native_splash: ^2.2.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_native_splash:
  color: "#FF0017"
  image: assets/png/Online.png

flutter: 
  uses-material-design: true
  assets:
   - assets/png/

